---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by glastis.
--- DateTime: 26-Nov-22 18:26
---

package.path = package.path .. ';/ComputerCraft/common/?.lua'

local sides = require 'sides'
local move = require 'move'
local inventory = require 'inventory'
local storage = require 'storage'

local FIELD_SIZE_X = 8
local FIELD_SIZE_Z = 8
local CROP_PROPERTIES = {name = 'mysticalagriculture:inferium_crop', stage = 7 }
local PRODUCT_PROPERTIES = {name = 'mysticalagriculture:inferium_essence' }
local SEED_PROPERTIES = {name = 'mysticalagriculture:inferium_seeds'}
local DELAY_GROWTH = 600

local function is_ready_to_harvest()
    local crop_properties

    _, crop_properties = turtle.inspectDown()
    return crop_properties and crop_properties.name == CROP_PROPERTIES.name and crop_properties.state and crop_properties.state.age == CROP_PROPERTIES.stage
end

local function harvest_and_plant_below()
    if is_ready_to_harvest() then
        turtle.digDown()
    end
    if inventory.select_item(SEED_PROPERTIES.name) then
        turtle.placeDown()
    end
end

local function get_seeds_from_chest()
    storage.suck(sides.left)
end

local function store_seeds_to_chest()
    inventory.drop_item(SEED_PROPERTIES.name, sides.left)
end

local function process_field()
    local to_z
    local to_x

    move.setCoords(0, 0, 0)
    to_z = 0
    while to_z <= FIELD_SIZE_Z do
        if (to_z % 2) == 0 then
            to_x = FIELD_SIZE_X
        else
            to_x = 0
        end
        if to_z ~= FIELD_SIZE_Z then
            move.move_to_and_execute(to_x, 0, to_z + 1, true, harvest_and_plant_below)
        else
            move.move_to_and_execute(to_x, 0, to_z, true, harvest_and_plant_below)
        end
        to_z = to_z + 1
    end
    move.move_to_and_execute(0, 0, 0, true, harvest_and_plant_below)
end

local function cleanup_inventory()
    inventory.drop_item(PRODUCT_PROPERTIES.name, sides.bottom)
    inventory.drop_all(sides.top)
end

local function go_to_field_from_start()
    move.up()
    move.forward(3)
end

local function go_to_start_from_field()
    move.backward(3)
    move.down()
    move.rotate(sides.front)
end

local function is_server_restart_hours()
    local hour

    hour = os.time("local")
    return hour >= 5 and hour <= 7
end

local function main()
    while true do
        if not is_server_restart_hours() then
            go_to_field_from_start()
            get_seeds_from_chest()
            process_field()
            store_seeds_to_chest()
            go_to_start_from_field()
            cleanup_inventory()
        end
        sleep(DELAY_GROWTH)
    end
end

main()