---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by glastis.
--- DateTime: 26-Nov-22 18:26
---

local sides = require 'sides'
local move = require 'move'
local inventory = require 'inventory'
local storage = require 'storage'

local FIELD_SIZE_X = 5
local FIELD_SIZE_Z = 5
local CROP_PROPERTIES = {name = "mysticalagriculture:inferium_crop", stage = 7}
local SEED_PROPERTIES = {name = "mysticalagriculture:inferium_seeds"}

local function is_ready_to_harvest()
    crop = turtle.inspectDown()
    return crop and crop.name == CROP_PROPERTIES.name and crop.state.stage == CROP_PROPERTIES.stage
end

local function harvest_and_plant_below()
    if is_ready_to_harvest() then
        turtle.digDown()
    end
    if inventory.select_item(SEED_PROPERTIES.name) then
        turtle.placeDown()
    end
end

local function get_seeds_from_chest()
    storage.suck(sides.left)
end

local function store_seeds_to_chest()
    inventory.drop_item(SEED_PROPERTIES.name, sides.left)
end

local function process_field()
    local y
    local x

    move.setCoords(0, 0, 0)
    y = 0
    x = 0
    while y < FIELD_SIZE_Z do
        move.move_to_and_execute(x, y, 0, true, harvest_and_plant_below)
        if x == 0 then
            x = FIELD_SIZE_X - 1
        else
            x = 0
        end
        y = y + 1
    end
    move.move_to_and_execute(0, 0, 0, true, harvest_and_plant_below)
end

local function cleanup_inventory()
    inventory.drop_item(CROP_PROPERTIES.name, sides.bottom)
    inventory.drop_all(sides.top)
end

local function go_to_field_from_start()
    move.up()
    move.forward(3)
end

local function go_to_start_from_field()
    move.back(3)
    move.down()
end

local function main()
    go_to_field_from_start()
    get_seeds_from_chest()
    process_field()
    store_seeds_to_chest()
    go_to_start_from_field()
    cleanup_inventory()
end

main()