---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by glastis.
--- DateTime: 26-Nov-22 18:26
---

package.path = package.path .. ';/ComputerCraft/common/?.lua'

local sides = require 'sides'
local move = require 'move'
local inventory = require 'inventory'
local storage = require 'storage'

local FIELD_SIZE_X = 8
local FIELD_SIZE_Z = 8
local DELAY_GROWTH = 10

local FIELD_HEIGHT = 4

local TOWERS = {}
local FIELDS = {}
FIELDS[#FIELDS + 1] = {}
FIELDS[#FIELDS].crop = {name = 'mysticalagriculture:inferium_crop', stage = 7 }
FIELDS[#FIELDS].product = {name = 'mysticalagriculture:inferium_essence' }
FIELDS[#FIELDS].seed = {name = 'mysticalagriculture:inferium_seeds'}
FIELDS[#FIELDS + 1] = FIELDS[#FIELDS]
FIELDS[#FIELDS + 1] = FIELDS[#FIELDS]
FIELDS[#FIELDS + 1] = FIELDS[#FIELDS]
FIELDS[#FIELDS + 1] = FIELDS[#FIELDS]
FIELDS[#FIELDS + 1] = FIELDS[#FIELDS]
FIELDS[#FIELDS + 1] = FIELDS[#FIELDS]
TOWERS[#TOWERS + 1] = FIELDS


local function is_ready_to_harvest(current_field_id)
    local crop_properties

    _, crop_properties = turtle.inspectDown()
    return crop_properties and crop_properties.name == FIELDS[current_field_id].crop.name and crop_properties.state and crop_properties.state.age == FIELDS[current_field_id].crop.stage
end

local function harvest_and_plant_below(current_field_id)
    if is_ready_to_harvest(current_field_id) then
        turtle.digDown()
    end
    if inventory.select_item(FIELDS[current_field_id].seed.name) then
        turtle.placeDown()
    end
end

local function get_seeds_from_chest()
    storage.suck(sides.left)
end

local function store_seeds_to_chest(current_field_id)
    inventory.drop_item(FIELDS[current_field_id].seed.name, sides.left)
end

local function process_field(current_field_id)
    local to_z
    local to_x

    move.setCoords(0, 0, 0)
    to_z = 0
    while to_z <= FIELD_SIZE_Z do
        if (to_z % 2) == 0 then
            to_x = FIELD_SIZE_X
        else
            to_x = 0
        end
        if to_z ~= FIELD_SIZE_Z then
            move.move_to_and_execute(to_x, 0, to_z + 1, true, harvest_and_plant_below, { current_field_id })
        else
            move.move_to_and_execute(to_x, 0, to_z, true, harvest_and_plant_below, { current_field_id })
        end
        to_z = to_z + 1
    end
    move.move_to_and_execute(0, 0, 0, true, harvest_and_plant_below, { current_field_id })
end

local function cleanup_inventory(current_field_id)
    inventory.drop_item(FIELDS[current_field_id].product.name, sides.bottom)
    inventory.drop_all(sides.top)
end

local function go_to_field_from_start(current_field_id)
    move.up(1 + (FIELD_HEIGHT * (current_field_id - 1)))
    move.forward(3)
end

local function go_to_start_from_field(current_field_id)
    move.backward(3)
    move.down(1 + (FIELD_HEIGHT * (current_field_id - 1)))
    move.rotate(sides.front)
end

local function is_server_restart_hours()
    local hour

    hour = os.time("local")
    return hour >= 10 and hour <= 12
end

local function main()
    local current_field_id

    current_field_id = 1
    while true do
        if not is_server_restart_hours() then
            go_to_field_from_start(current_field_id)
            get_seeds_from_chest()
            process_field(current_field_id)
            store_seeds_to_chest(current_field_id)
            go_to_start_from_field(current_field_id)
            cleanup_inventory(current_field_id)
            current_field_id = current_field_id + 1
            if current_field_id > #FIELDS then
                current_field_id = 1
            end
        end
        sleep(DELAY_GROWTH)
    end
end

main()