local constants = {}

constants.TURTLE_INVENTORY_LINE = 4
constants.TURTLE_INVENTORY_COLUMN = 4
constants.TURTLE_INVENTORY_SIZE = constants.TURTLE_INVENTORY_COLUMN * constants.TURTLE_INVENTORY_LINE

constants.CRAFTING_TABLE_LINE = 3
constants.CRAFTING_TABLE_COLUMN = 3
constants.CRAFTING_TABLE_SIZE = constants.CRAFTING_TABLE_COLUMN * constants.CRAFTING_TABLE_LINE

constants.MAX_STACK_SIZE_IN_MODPACK = 64

return constants