---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by glastis.
--- DateTime: 20-Nov-22 20:37
---

local sides = {}

sides.front = 0
sides.back = 1
sides.left = 2
sides.right = 3
sides.up = 4
sides.down = 5

sides.top = sides.up
sides.bottom = sides.down

return sides