---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by glastis.
--- DateTime: 26-Nov-22 20:09
---


local sides = require 'sides'
local move = require 'move'

local storage = {}

-------------------------------------------------------------------[[
---------------------------------------------------------------------
----                    PRIVATE FUNCTIONS                        ----
---------------------------------------------------------------------
-------------------------------------------------------------------]]


local function _convert_side_to_suck_function(side)
    if side <= 3 then
        return turtle.suck
    elseif side == sides.up then
        return turtle.suckUp
    elseif side == sides.down then
        return turtle.suckDown
    else
        print("Error: _convert_side_to_suck_function: side '" .. side .. "' is invalid")
        return nil
    end
end


-------------------------------------------------------------------[[
---------------------------------------------------------------------
----                    PUBLIC FUNCTIONS                         ----
---------------------------------------------------------------------
-------------------------------------------------------------------]]

--[[
---- Suck from the specified side. If no side is specified, suck from the front.
----
---- @param side   The side to suck from. If no side is specified, suck from the front.
---- @param amount The amount of items to suck. If no amount is specified, suck 1 item.
---- @return       The amount of items sucked.
--]]
local function suck(side, amount)
    local ret

    if not side then
        side = sides.front
    end
    move.rotate(side)
    ret = _convert_side_to_suck_function(side)(amount)
    move.rotate(sides.front)
    return ret
end
storage.suck = suck

return storage